[package]
name = "ip-tcp"
version = "0.1.0"
authors = ["Kartik Singhal <kartiksinghal@gmail.com>", "Sumukha TV <tvsumukha@gmail.com>"]

[dependencies]
env_logger = "0.3"
log = "0.3"

[dependencies.clap]
version = "2"
default-features = false

[[bin]]
name = "node"
path = "src/main.rs"

[dependencies.pnet]
version = "0.13.0"
